### ISSUE TITLE
Anchorpoint is not saved in symbols with type TRUETYPE

### ISSUE THREAD

**Issue by MaklariAgoston** [DMS-Aus/MapManager#17]
After saving a map file containing TRUETYPE symbol definitions with ANCHORPOINT, the anchorpoint is missing:

Example: Before save
 SYMBOL
    NAME "2"
    TYPE TRUETYPE
    CHARACTER "A"
    ANCHORPOINT 0 1
    FONT "alfa"
  END

After save
 SYMBOL
    NAME "2"
    TYPE TRUETYPE
    CHARACTER "A"  
    FONT "alfa"
  END

The same phenomenon occurs when I switch to the map and back to the text of the map file.
That is why I cannot use anchorpoint with this kind of Symbols, but for example with VECTOR type symbols everything works well.

**Comment by szekerest** [comment]
This has already been fixed within the scope of this bug:
https://github.com/mapserver/mapserver/issues/5073

**Comment by MaklariAgoston** [comment]
This bug is only partially fixed as if someone set an anchorpoint for a TRUETYPE in code than it will still not saved in the map file because in the map server's mapsymbol.c file has a writeSymbol function where missing the following part:

 if(s->anchorpoint_y!=0.5 || s->anchorpoint_x!=0.5) {
        msIO_fprintf(stream, "    ANCHORPOINT %g %g\n", s->anchorpoint_x, s->anchorpoint_y);
 }
 from the case section of MS_SYMBOL_TRUETYPE:
...
 case(MS_SYMBOL_TRUETYPE):
      msIO_fprintf(stream, "    TYPE TRUETYPE\n");
      if (s->character != NULL) msIO_fprintf(stream, "    CHARACTER \"%s\"\n", s->character);
      if (s->font != NULL) msIO_fprintf(stream, "    FONT \"%s\"\n", s->font);
      break;
...

Anyway the behaviour is already ok if you edit and save the map file by hand in the Map Manager.
