### ISSUE TITLE
Style properties - Fill Patterns does not work

### ISSUE THREAD

**Issue by MicheleFioretto** [DMS-Aus/MapManager#19]
I'm using mapmanger version:
MapServer version 7.0.1
GDAL 2.1.0, released 2016/04/25
proj Rel. 4.8.0, 6 March 2012
geos 3.4.3-CAPI-1.8.3 r4038
zlib 1.2.3
libcurl/7.37.1 OpenSSL/1.0.1h zlib/1.2.3

I'm not able to make a fill patterns other than defaults (ex. Horizontal-1). 
See the images attached to this issue. 
Please correct me if I'm wrong

Many thanks
Michele

This is wrong:
![mapmanager-issue](https://cloud.githubusercontent.com/assets/3819583/18118101/1b13018a-6f53-11e6-9e0e-7701a3480e6e.png)

This is ok:
![mapmanager-ok](https://cloud.githubusercontent.com/assets/3819583/18118115/30ecc2fc-6f53-11e6-9970-c3772483b621.png)

**Comment by stephdms** [comment]
Hey Michele
It would appear that background colour and your colour on the first shot are the same (grey), try different ones.
also to get outline colour you need to create a second style and set the outline colour, while keeping background and colour blank (transparent), this is what mapserver wants ultimately.

**Comment by MicheleFioretto** [comment]
ok thanks, I was missing this:
_"also to get outline colour you need to create a second style and set the outline colour, while keeping background and colour blank (transparent), this is what mapserver wants ultimately."_
michele
