### ISSUE TITLE
Confused rendering of selected features with changed class order

### ISSUE THREAD

**Issue by MaklariAgoston** [DMS-Aus/MapManager#23]
Select 3 features (the first 3 in the list on the left):

![selectedfeaturesbasestatus](https://cloud.githubusercontent.com/assets/19466622/18739089/4dc61d9c-80a1-11e6-8c39-9e6e0095743b.png)
Drag the 3rd in the row over the 1st one and you will see:
![selectedfeatures1stpermutation](https://cloud.githubusercontent.com/assets/19466622/18739166/edd20f08-80a1-11e6-9392-38e648514737.png)
In this first permutation we can see that the Road became Train, the Highway became Road and the Train became Highway.
Now do the same again (put the third to the first place):
![selectedfeatures2ndpermutation](https://cloud.githubusercontent.com/assets/19466622/18739308/e06606d4-80a2-11e6-8f4a-489f27feec84.png)
In the second permutation the Road became Highway, the Highway became Train and the Train became Road.
Now if you do the same again you will see everything get back to the first original situation

**Comment by szekerest** [comment]
Since the layer and class index is not valid in the result set after reordering the layers/classes, the most reasonable solution is to clear the resultset in these cases.
