### ISSUE TITLE
A vector file cannot be opened in a folder named with accentuated letters.

### ISSUE THREAD

**Issue by MaklariAgoston** [DMS-Aus/MapManager#25]
![addvectorfile](https://cloud.githubusercontent.com/assets/19466622/20137816/1dfed2fa-a67d-11e6-979e-448699a7a22b.png)

Trying to open a vector file in a folder named with accentuated letters you will get the following error message:

![ekezetesbetuk](https://cloud.githubusercontent.com/assets/19466622/20137819/22a0fc0c-a67d-11e6-9c8e-e0e2de98e9cb.png)

**Comment by szekerest** [comment]
This issue was already fixed

**Comment by szekerest** [comment]
related issue in mapserver https://github.com/mapserver/mapserver/issues/5995
