### ISSUE TITLE
Missing inline symbol definitions after setting the Map scale for a smaller value

### ISSUE THREAD

**Issue by MaklariAgoston** [DMS-Aus/MapManager#26]
Set the Map scale for a smaller value e.g. from 30227 to 30000 and push the Apply button.

All the symbol definitions are missing from the map file and due to this you get an error message:
![missingsymbols](https://cloud.githubusercontent.com/assets/19466622/20430968/bc5f8f68-ad97-11e6-8a35-e4bbcdd22084.png)

The consequence is very similar to the phemomenon of the issue #22.

**Comment by szekerest** [comment]
Relative path handling has already been fixed
