### ISSUE TITLE
In a rotated map the select function does not select point feature

### ISSUE THREAD

**Issue by MaklariAgoston** [DMS-Aus/MapManager#27]
Trying to select a point feature does not work if the ANGLE is not 0 in map file.

The coordinates of the same point with 0 degree rotation are:
256443 5212654
but with a 90 degree rotation they are:
256553 5212559
with a 1454 zoom value (though I used the pawn cursor for getting these coordinates, these differents are too great)

![selectednotrotated](https://cloud.githubusercontent.com/assets/19466622/22686557/d221bbec-ed24-11e6-8886-7e2a662dcb44.png)
Result of the selection without rotation

![selectingrotated90degree](https://cloud.githubusercontent.com/assets/19466622/22686561/d52ad6ac-ed24-11e6-80b0-b088658e6254.png)
The selecting with 90 degree rotation

![resultofselectionrotated90degree](https://cloud.githubusercontent.com/assets/19466622/22686566/d7e6bfe6-ed24-11e6-9a8f-d6ed71cda618.png)
Result of the selection with 90 degree rotation

**Comment by szekerest** [comment]
Fixed
