### ISSUE TITLE
Pan function does not work correctly on rotated maps 

### ISSUE THREAD

**Issue by MaklariAgoston** [DMS-Aus/MapManager#28]
Set ANGLE 90 for the rotation of the map in the map file!

Choose the Pan function due to move the map by drag-and-drop!

If you try to move the map to the north with a downward directed drag-and-drop operation than the map move to the east with the same distance.

![dragstartpositionwith90degreerotation](https://cloud.githubusercontent.com/assets/19466622/22687037/bf768d72-ed26-11e6-8c5d-4df9473352b2.png)
Before

![dragendpositionwith90degreerotation](https://cloud.githubusercontent.com/assets/19466622/22687038/c16284c4-ed26-11e6-9893-854b72584574.png)
After

The blue cross show the center of the screen.

**Comment by szekerest** [comment]
Issue opened in mapserver https://github.com/mapserver/mapserver/issues/6046
