### ISSUE TITLE
Installation on  windows 10 home edition

### ISSUE THREAD

**Issue by ghost** [DMS-Aus/MapManager#29]
Hi

Using the mapmanger.mis.exe on windows 10 home edition, displays a message stating this software
cannot run on this PC. Will there be a version to run on windows 10 home edition?
If not what is required to compile the software on windows 10 home edition?

Thanks

Aimee

**Comment by szekerest** [comment]
Did you try with the latest msi installer?
http://www.gisinternals.com/sdk/downloads/release-1600-gdal-2-1-mapserver-7-0/MapManager.msi

**Comment by ghost** [comment]
Hi

yes, just dloaded, same issue.

Tks

Aimee

**Comment by bzeeb** [comment]
Issue is most likely .Net 2/3.5 not installed on PC.

I have no experience with Windows 10 home, in pro version we would simply go in to add/remove features and tick on the older version of .net.

MapManager should be built against .net 4.5.2 in the future which would resolve the issue.

**Comment by ghost** [comment]
Hi

Thanks for your reply. I have checked the system and .NET 2/3.5 is installed, however
the same problem occurs (yes did the mandatory reboot!!)

I assume you have no problem on W10 Pro version?

I am unable to rebuild it (did try with the 30 day Visual Studio but not successful,
my background is Unix so its all a bit weird to me)

Silly thing is the only reason for having a W10 box is to support some software
that no longer works under XP, which was the last version installed here.

I can only hope someone can recompile it with .NET 4., till then, editing the MAP files with nano!!


Thanks

Aimee

**Comment by samtux** [comment]
I have done the installation with the custom settings and it works correctly for me:

![Mapserver7](https://i.imgur.com/EZo5tyk.png)

I disabled the Mapsever plugins and GDAL plugins options

**Comment by ghost** [comment]
Hi

Thanks for that. Can confirm that using the last but one version it opens up ok, the latest did not.
Having looked at it, it will take a bit of tweaking to get my map working as its on a unix system, and the editor seems to be very Windows centric. 
Thanks

Aimee

**Comment by szekerest** [comment]
Published MapManager v1.1 build with VS2015
hope that will solve the problems

**Comment by ghost** [comment]
Latest Version downloaded now works, Thanks
