### ISSUE TITLE
msProcessProjection() Error for "init=epsg:900913.

### ISSUE THREAD

**Issue by bozhidarc** [DMS-Aus/MapManager#3]
When I try to open a mapfile with PROJECTION  set to "init=epsg:900913" the following error is thrown:

![error](https://cloud.githubusercontent.com/assets/323252/5645593/6eceb3f4-967a-11e4-8c78-59711f699e82.JPG)

I try to add the projection definition in c:\Program Files (x86)\MapManager\ProjLib\epsg file but without success. 

```
#900913
<900913> +proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids= <at> null +no_defs <>
```

**Comment by szekerest** [comment]
Just applied a fix to process the last line of the EPSG file.
Regarding to this problem you are recommended to use the official EPSG:3857 code instead.
