### ISSUE TITLE
Does MapManager manage includes?

### ISSUE THREAD

**Issue by pelord** [DMS-Aus/MapManager#30]
To create large mapfiles as simple as possible, I frequently incorporate include as :

    INCLUDE "../ec/connec_db_pg.map"

Does MapManager can manage them?
I know, that it's more a question than an issue.

**Comment by szekerest** [comment]
Currently this can only be done in the text tab. 
What kind of functionality should be added? Just to add/remove the includes or support for editing multiple map files within the same application?

**Comment by pelord** [comment]
I'm not really familiar with MapManager but to you think it is possible for MapManager to inherit parent mapfiles?  It's more this kind of include I am looking for?

**Comment by KenHeer1** [comment]
My use case would benefit from this as well.

I'm using includes in 2 ways; one for connection strings and one for "members". Members is basically a group of layers specific to a group. So our primary mapfile has the main mapfile details, then all the layers are grouped into separate .map files and included into the main one. 

I don't know if my specific use case is broad enough, but I'm thinking something like adding a context menu item to add include file. When attempted, if the main map file and the newly included map file parses, then maybe add the included map file as an additional tab? The title of the "Text" tab could be updated to the name of the main map file. Really just thinking out loud.

**Comment by szekerest** [comment]
Sounds like a good enhancement, but it would be hard to implement, since the include information is lost when the mapfile was parsed. When we save that mapfile again, the resulting file would contain merged data from the base file and the linked files.
