### ISSUE TITLE
Add capability to feature sub-class on an attribute

### ISSUE THREAD

**Issue by damiandixon** [DMS-Aus/MapManager#31]
If I have a shapefile with an attribute field 'fclass' I would like to create as many sub-classes as there are unique values.

Ideally I would like the rendering to be set to that of the parent initially.

**Comment by szekerest** [comment]
In MapManager by using the "Add Theme Wizard" you can generate classes for each individual values of the selected attribute. Is that sufficient for the purpose?

**Comment by damiandixon** [comment]
This is just what I was looking for. Thanks.
