### ISSUE TITLE
MapManager crashes if shapefile does not have PRJ file

### ISSUE THREAD

**Issue by sggreener** [DMS-Aus/MapManager#39]
MapServer version 8.0.0
GDAL 3.6.3, released 2023/02/23
proj Rel. 9.1.1, December 1st, 2022
geos 3.10.2-CAPI-1.16.0
zlib 1.2.11
libcurl/7.79.1-DEV OpenSSL/1.1.1l zlib/1.2.11

Steps to replicate:

1. Create empty map file
2. Add a shapefile without a PROJ

Simon

**Comment by szekerest** [comment]
Fixed
